utils: Remove modernizr, which still uses requirejs and gives a bunch of errors on importing
These were the errors with Modernizr 3.7.1:
  ● Test suite failed to run

    :2
    }(requirejsVars.require, requirejsVars.requirejs, requirejsVars.define));
      ^

    ReferenceError: requirejsVars is not defined

      at exec (node_modules/requirejs/bin/r.js:62:23)
      at setBaseUrl (node_modules/requirejs/bin/r.js:30248:13)
      at node_modules/requirejs/bin/r.js:30338:9
      at Object.<anonymous> (node_modules/requirejs/bin/r.js:30427:2)